-- MySQL Script generated by MySQL Workbench
-- 01/16/15 02:01:13
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Lattes
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Lattes` ;
CREATE SCHEMA IF NOT EXISTS `Lattes` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Lattes` ;

-- -----------------------------------------------------
-- Table `dim_pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dim_pessoa` ;

CREATE TABLE IF NOT EXISTS `dim_pessoa` (
  `id_user` BIGINT NOT NULL,
  `nm_user` VARCHAR(150) NOT NULL,
  `citacao` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dim_tempo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dim_tempo` ;

CREATE TABLE IF NOT EXISTS `dim_tempo` (
  `id_tempo` INT NOT NULL AUTO_INCREMENT,
  `ano_inicial` INT NOT NULL,
  `mes_inicial` INT NULL,
  `ano_final` INT NULL,
  `mes_final` INT NULL,
  PRIMARY KEY (`id_tempo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat_projeto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat_projeto` ;

CREATE TABLE IF NOT EXISTS `fat_projeto` (
  `id_user` BIGINT NOT NULL,
  `id_tempo` INT NOT NULL,
  `tipo` LONGTEXT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` LONGTEXT NULL,
  `situacao` VARCHAR(100) NULL,
  `natureza` VARCHAR(100) NULL,
  `alunos` VARCHAR(255) NULL,
  `integrantes` LONGTEXT NULL,
  `financiador` VARCHAR(255) NULL,
  `producoes` INT NULL,
  INDEX `fk_Projetos_Tempo1_idx` (`id_tempo` ASC),
  PRIMARY KEY (`id_user`, `id_tempo`),
  INDEX `fk_Projetos_dim_Pessoa1_idx` (`id_user` ASC),
  CONSTRAINT `fk_Projetos_Tempo1`
    FOREIGN KEY (`id_tempo`)
    REFERENCES `dim_tempo` (`id_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projetos_dim_Pessoa1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dim_pessoa` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat_formacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat_formacao` ;

CREATE TABLE IF NOT EXISTS `fat_formacao` (
  `id_user` BIGINT NOT NULL,
  `id_tempo` INT NOT NULL,
  `nivel` LONGTEXT NOT NULL,
  `curso` LONGTEXT NOT NULL,
  `local` VARCHAR(255) NOT NULL,
  `titulo` VARCHAR(255) NULL,
  `orientador` VARCHAR(255) NULL,
  `bolsa` VARCHAR(45) NULL,
  `keywords` LONGTEXT NULL,
  `areas` LONGTEXT NULL,
  `setor` VARCHAR(255) NULL,
  PRIMARY KEY (`id_user`, `id_tempo`),
  INDEX `fk_Formacao_Geral_idx` (`id_user` ASC),
  INDEX `fk_Formacao_Tempo1_idx` (`id_tempo` ASC),
  CONSTRAINT `fk_Formacao_Geral`
    FOREIGN KEY (`id_user`)
    REFERENCES `dim_pessoa` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Formacao_Tempo1`
    FOREIGN KEY (`id_tempo`)
    REFERENCES `dim_tempo` (`id_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat_atuacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat_atuacao` ;

CREATE TABLE IF NOT EXISTS `fat_atuacao` (
  `id_user` BIGINT NOT NULL,
  `id_tempo` INT NOT NULL,
  `instituicao` VARCHAR(150) NOT NULL,
  `tipo_vinculo` VARCHAR(45) NULL,
  `vinculo_empregaticio` TINYINT(1) NULL,
  `enq_funcional` VARCHAR(45) NULL,
  `carga_horaria` INT NULL,
  INDEX `fk_Atuacao_Geral1_idx` (`id_user` ASC),
  INDEX `fk_Atuacao_Tempo1_idx` (`id_tempo` ASC),
  PRIMARY KEY (`id_user`, `id_tempo`),
  CONSTRAINT `fk_Atuacao_Geral1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dim_pessoa` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Atuacao_Tempo1`
    FOREIGN KEY (`id_tempo`)
    REFERENCES `dim_tempo` (`id_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dim_cadastro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dim_cadastro` ;

CREATE TABLE IF NOT EXISTS `dim_cadastro` (
  `id_dataCadastro` INT NOT NULL AUTO_INCREMENT,
  `data_cadastro` DATE NOT NULL,
  PRIMARY KEY (`id_dataCadastro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat_idioma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat_idioma` ;

CREATE TABLE IF NOT EXISTS `fat_idioma` (
  `id_user` BIGINT NOT NULL,
  `data_cadastro` INT NOT NULL,
  `idioma` VARCHAR(45) NOT NULL,
  `le` VARCHAR(45) NOT NULL,
  `fala` VARCHAR(45) NOT NULL,
  `escreve` VARCHAR(45) NOT NULL,
  `compreende` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user`, `data_cadastro`),
  INDEX `fk_idioma_Geral1_idx` (`id_user` ASC),
  INDEX `fk_fat_idioma_dim_cadastro1_idx` (`data_cadastro` ASC),
  CONSTRAINT `fk_idioma_Geral1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dim_pessoa` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fat_idioma_dim_cadastro1`
    FOREIGN KEY (`data_cadastro`)
    REFERENCES `dim_cadastro` (`id_dataCadastro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat_pesquisa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat_pesquisa` ;

CREATE TABLE IF NOT EXISTS `fat_pesquisa` (
  `id_user` BIGINT NOT NULL,
  `data_cadastro` INT NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_user`, `data_cadastro`),
  INDEX `fk_Pesquisa_Geral1_idx` (`id_user` ASC),
  INDEX `fk_fat_pesquisa_dim_cadastro1_idx` (`data_cadastro` ASC),
  CONSTRAINT `fk_Pesquisa_Geral1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dim_pessoa` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fat_pesquisa_dim_cadastro1`
    FOREIGN KEY (`data_cadastro`)
    REFERENCES `dim_cadastro` (`id_dataCadastro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ref_endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ref_endereco` ;

CREATE TABLE IF NOT EXISTS `ref_endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `id_user` BIGINT NOT NULL,
  `cep` INT NOT NULL,
  `estado` VARCHAR(2) NULL,
  `cidade` VARCHAR(150) NULL,
  `bairro` VARCHAR(150) NULL,
  `rua` VARCHAR(150) NULL,
  `num` INT NULL,
  PRIMARY KEY (`id_endereco`),
  INDEX `fk_ref_Endereco_dim_pessoa1_idx` (`id_user` ASC),
  CONSTRAINT `fk_ref_Endereco_dim_pessoa1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dim_pessoa` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat_premio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat_premio` ;

CREATE TABLE IF NOT EXISTS `fat_premio` (
  `id_user` BIGINT NOT NULL,
  `id_tempo` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `entidade` VARCHAR(45) NOT NULL,
  INDEX `fk_Premios_Tempo1_idx` (`id_tempo` ASC),
  INDEX `fk_Premios_Geral1_idx` (`id_user` ASC),
  PRIMARY KEY (`id_user`, `id_tempo`),
  CONSTRAINT `fk_Premios_Tempo1`
    FOREIGN KEY (`id_tempo`)
    REFERENCES `dim_tempo` (`id_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Premios_Geral1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dim_pessoa` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curriculum`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curriculum` ;

CREATE TABLE IF NOT EXISTS `curriculum` (
  `data_cadastro` INT NOT NULL,
  `id_curriculo` BIGINT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `url` VARCHAR(200) NOT NULL,
  `content` BLOB NOT NULL,
  PRIMARY KEY (`id_curriculo`, `data_cadastro`),
  INDEX `fk_curriculum_dim_cadastro1_idx` (`data_cadastro` ASC),
  CONSTRAINT `fk_curriculum_dim_cadastro1`
    FOREIGN KEY (`data_cadastro`)
    REFERENCES `dim_cadastro` (`id_dataCadastro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat_corpoEditorial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat_corpoEditorial` ;

CREATE TABLE IF NOT EXISTS `fat_corpoEditorial` (
  `id_user` BIGINT NOT NULL,
  `id_tempo` INT NOT NULL,
  `editorial` LONGTEXT NOT NULL,
  INDEX `fk_CorpoEditorial_Tempo1_idx` (`id_tempo` ASC),
  PRIMARY KEY (`id_user`, `id_tempo`),
  INDEX `fk_CorpoEditorial_Geral1_idx` (`id_user` ASC),
  CONSTRAINT `fk_CorpoEditorial_Tempo1`
    FOREIGN KEY (`id_tempo`)
    REFERENCES `dim_tempo` (`id_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CorpoEditorial_Geral1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dim_pessoa` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat_revisor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat_revisor` ;

CREATE TABLE IF NOT EXISTS `fat_revisor` (
  `id_user` BIGINT NOT NULL,
  `id_tempo` INT NOT NULL,
  `periodico` BLOB NULL,
  `tipo_revisao` VARCHAR(45) NULL,
  `instituicao` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user`, `id_tempo`),
  INDEX `fk_RevisorPeriodico_Tempo1_idx` (`id_tempo` ASC),
  INDEX `fk_RevisorPeriodico_Geral1_idx` (`id_user` ASC),
  CONSTRAINT `fk_RevisorPeriodico_Tempo1`
    FOREIGN KEY (`id_tempo`)
    REFERENCES `dim_tempo` (`id_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RevisorPeriodico_Geral1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dim_pessoa` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat_producao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat_producao` ;

CREATE TABLE IF NOT EXISTS `fat_producao` (
  `id_user` BIGINT NOT NULL,
  `id_tempo` INT NOT NULL,
  `titulo` BLOB NOT NULL,
  `volume` INT NULL,
  `pagina` INT NULL,
  `keywords` VARCHAR(45) NULL,
  `url` VARCHAR(255) NULL,
  `tipo` VARCHAR(45) NULL,
  `serie` VARCHAR(45) NULL,
  `issn_isbn` VARCHAR(45) NULL,
  `divisao` VARCHAR(45) NULL,
  `areas` BLOB NULL,
  INDEX `fk_Producoes_Tempo1_idx` (`id_tempo` ASC),
  INDEX `fk_Producoes_Geral1_idx` (`id_user` ASC),
  PRIMARY KEY (`id_user`, `id_tempo`),
  CONSTRAINT `fk_Producoes_Tempo1`
    FOREIGN KEY (`id_tempo`)
    REFERENCES `dim_tempo` (`id_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producoes_Geral1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dim_pessoa` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat_banca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat_banca` ;

CREATE TABLE IF NOT EXISTS `fat_banca` (
  `id_user` BIGINT NOT NULL,
  `id_tempo` INT NOT NULL,
  `tipo` LONGTEXT NOT NULL,
  `banca` VARCHAR(255) NULL,
  `titulo` VARCHAR(255) NULL,
  `ano` VARCHAR(255) NULL,
  `sobre` LONGTEXT NULL,
  PRIMARY KEY (`id_user`, `id_tempo`),
  INDEX `fk_Bancas_Tempo1_idx` (`id_tempo` ASC),
  INDEX `fk_Bancas_Geral1_idx` (`id_user` ASC),
  CONSTRAINT `fk_Bancas_Tempo1`
    FOREIGN KEY (`id_tempo`)
    REFERENCES `dim_tempo` (`id_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bancas_Geral1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dim_pessoa` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat_evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat_evento` ;

CREATE TABLE IF NOT EXISTS `fat_evento` (
  `id_user` BIGINT NOT NULL,
  `id_tempo` INT NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  `adicionais` LONGTEXT NULL,
  `tipo` VARCHAR(45) NULL,
  `forma` VARCHAR(45) NULL,
  `url` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tempo`, `id_user`),
  INDEX `fk_Eventos_Tempo1_idx` (`id_tempo` ASC),
  INDEX `fk_Eventos_dim_Pessoa1_idx` (`id_user` ASC),
  CONSTRAINT `fk_Eventos_Tempo1`
    FOREIGN KEY (`id_tempo`)
    REFERENCES `dim_tempo` (`id_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Eventos_dim_Pessoa1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dim_pessoa` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat_orientacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat_orientacao` ;

CREATE TABLE IF NOT EXISTS `fat_orientacao` (
  `id_user` BIGINT NOT NULL,
  `id_tempo` INT NOT NULL,
  `orientado` VARCHAR(150) NULL,
  `descricao` LONGTEXT NULL,
  `tipo` VARCHAR(45) NULL,
  `local` VARCHAR(255) NULL,
  `keywords` LONGTEXT NULL,
  `adicionais` LONGTEXT NULL,
  PRIMARY KEY (`id_user`, `id_tempo`),
  INDEX `fk_Orientacoes_Tempo2_idx` (`id_tempo` ASC),
  INDEX `fk_Orientacoes_Geral2_idx` (`id_user` ASC),
  CONSTRAINT `fk_Orientacoes_Tempo2`
    FOREIGN KEY (`id_tempo`)
    REFERENCES `dim_tempo` (`id_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orientacoes_Geral2`
    FOREIGN KEY (`id_user`)
    REFERENCES `dim_pessoa` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `link`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `link` ;

CREATE TABLE IF NOT EXISTS `link` (
  `id_link` BIGINT NOT NULL,
  `url` VARCHAR(250) NOT NULL,
  `data_cur` DATE NULL,
  PRIMARY KEY (`id_link`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fila_process`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fila_process` ;

CREATE TABLE IF NOT EXISTS `fila_process` (
  `url` VARCHAR(255) NOT NULL,
  `log` BLOB NULL,
  PRIMARY KEY (`url`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat_patente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat_patente` ;

CREATE TABLE IF NOT EXISTS `fat_patente` (
  `id_user` BIGINT NOT NULL,
  `id_tempo` INT NOT NULL,
  `titulo` LONGTEXT NOT NULL,
  `patente` VARCHAR(255) NULL,
  `numero` VARCHAR(255) NULL,
  `data_deposito` DATE NULL,
  `instituicao` LONGTEXT NULL,
  INDEX `fk_Patentes_dim_tempo1_idx` (`id_tempo` ASC),
  INDEX `fk_Patentes_dim_pessoa1_idx` (`id_user` ASC),
  PRIMARY KEY (`id_user`, `id_tempo`),
  CONSTRAINT `fk_Patentes_dim_tempo1`
    FOREIGN KEY (`id_tempo`)
    REFERENCES `dim_tempo` (`id_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Patentes_dim_pessoa1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dim_pessoa` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat_area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat_area` ;

CREATE TABLE IF NOT EXISTS `fat_area` (
  `id_user` BIGINT NOT NULL,
  `data_cadastro` INT NOT NULL,
  `grande_area` VARCHAR(255) NOT NULL,
  `sub_area` VARCHAR(255) NOT NULL,
  INDEX `fk_fat_area_dim_pessoa1_idx` (`id_user` ASC),
  PRIMARY KEY (`id_user`, `data_cadastro`),
  INDEX `fk_fat_area_dim_cadastro1_idx` (`data_cadastro` ASC),
  CONSTRAINT `fk_fat_area_dim_pessoa1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dim_pessoa` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fat_area_dim_cadastro1`
    FOREIGN KEY (`data_cadastro`)
    REFERENCES `dim_cadastro` (`id_dataCadastro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat_educacaoPopularizacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat_educacaoPopularizacao` ;

CREATE TABLE IF NOT EXISTS `fat_educacaoPopularizacao` (
  `id_user` BIGINT NOT NULL,
  `id_tempo` INT NOT NULL,
  `participantes` VARCHAR(255) NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  `tipo` VARCHAR(255) NOT NULL,
  INDEX `fk_fat_educacaoPopularizacao_dim_pessoa1_idx` (`id_user` ASC),
  INDEX `fk_fat_educacaoPopularizacao_dim_tempo1_idx` (`id_tempo` ASC),
  PRIMARY KEY (`id_tempo`, `id_user`),
  CONSTRAINT `fk_fat_educacaoPopularizacao_dim_pessoa1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dim_pessoa` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fat_educacaoPopularizacao_dim_tempo1`
    FOREIGN KEY (`id_tempo`)
    REFERENCES `dim_tempo` (`id_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ref_informacoesAdicionais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ref_informacoesAdicionais` ;

CREATE TABLE IF NOT EXISTS `ref_informacoesAdicionais` (
  `id_user` BIGINT NOT NULL,
  `id_informacao` INT NOT NULL AUTO_INCREMENT,
  `informacao` LONGTEXT NOT NULL,
  INDEX `fk_informacoes_adicionais_dim_pessoa1_idx` (`id_user` ASC),
  PRIMARY KEY (`id_informacao`, `id_user`),
  CONSTRAINT `fk_informacoes_adicionais_dim_pessoa1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dim_pessoa` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



INSERT INTO `link` (id_link, url, data_cur) VALUES (3036922516937013,'http://lattes.cnpq.br/3036922516937013 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0135813952022069,'http://lattes.cnpq.br/0135813952022069 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (1499255840548015,'http://lattes.cnpq.br/1499255840548015 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (7586240232439023,'http://lattes.cnpq.br/7586240232439023 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (2559443073447665,'http://lattes.cnpq.br/2559443073447665 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5684844466181528,'http://lattes.cnpq.br/5684844466181528 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5330935294822485,'http://lattes.cnpq.br/5330935294822485 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5647518666766098,'http://lattes.cnpq.br/5647518666766098 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3055017593899202,'http://lattes.cnpq.br/3055017593899202 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0530746850858281,'http://lattes.cnpq.br/0530746850858281 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (4537202182497136,'http://lattes.cnpq.br/4537202182497136 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (4813776040721321,'http://lattes.cnpq.br/4813776040721321 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (9375203970777529,'http://lattes.cnpq.br/9375203970777529 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (4184200727895135,'http://lattes.cnpq.br/4184200727895135 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5492868617484949,'http://lattes.cnpq.br/5492868617484949 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (7835878522109146,'http://lattes.cnpq.br/7835878522109146 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (6994711731969765,'http://lattes.cnpq.br/6994711731969765 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (7809788419483288,'http://lattes.cnpq.br/7809788419483288 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3271813807797335,'http://lattes.cnpq.br/3271813807797335 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5602167244336832,'http://lattes.cnpq.br/5602167244336832 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (1723588689819867,'http://lattes.cnpq.br/1723588689819867 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (2557440893085062,'http://lattes.cnpq.br/2557440893085062 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (9162672829956114,'http://lattes.cnpq.br/9162672829956114 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5392241127647379,'http://lattes.cnpq.br/5392241127647379 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (9815991816629677,'http://lattes.cnpq.br/9815991816629677 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0586192294187200,'http://lattes.cnpq.br/0586192294187200 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5408753184399257,'http://lattes.cnpq.br/5408753184399257 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5323510575674245,'http://lattes.cnpq.br/5323510575674245 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0940496547256243,'http://lattes.cnpq.br/0940496547256243 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (8106581881944311,'http://lattes.cnpq.br/8106581881944311 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5552798921442636,'http://lattes.cnpq.br/5552798921442636 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3077322810859474,'http://lattes.cnpq.br/3077322810859474 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (8281938994335008,'http://lattes.cnpq.br/8281938994335008 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (1843622722501234,'http://lattes.cnpq.br/1843622722501234 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (7238676641856131,'http://lattes.cnpq.br/7238676641856131 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (6255983361952112,'http://lattes.cnpq.br/6255983361952112 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0100900666337016,'http://lattes.cnpq.br/0100900666337016 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (4486245273498923,'http://lattes.cnpq.br/4486245273498923 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (7799906288400968,'http://lattes.cnpq.br/7799906288400968 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (8337771861251036,'http://lattes.cnpq.br/8337771861251036 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3785730549168231,'http://lattes.cnpq.br/3785730549168231 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (1792205990988340,'http://lattes.cnpq.br/1792205990988340 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (9195827067481746,'http://lattes.cnpq.br/9195827067481746 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0429482181200294,'http://lattes.cnpq.br/0429482181200294 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (1680435420456224,'http://lattes.cnpq.br/1680435420456224 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (4101528924530251,'http://lattes.cnpq.br/4101528924530251 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5512756726602398,'http://lattes.cnpq.br/5512756726602398 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (2958968230286675,'http://lattes.cnpq.br/2958968230286675 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (9372771098481985,'http://lattes.cnpq.br/9372771098481985 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (7275780893907716,'http://lattes.cnpq.br/7275780893907716 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (8256920836735279,'http://lattes.cnpq.br/8256920836735279 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0933645512348500,'http://lattes.cnpq.br/0933645512348500 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (1777689849515474,'http://lattes.cnpq.br/1777689849515474 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3044299425417905,'http://lattes.cnpq.br/3044299425417905 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (8955775908880210,'http://lattes.cnpq.br/8955775908880210 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0923886564574568,'http://lattes.cnpq.br/0923886564574568 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (2704773293662530,'http://lattes.cnpq.br/2704773293662530 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (6098762845774771,'http://lattes.cnpq.br/6098762845774771 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3419623398527291,'http://lattes.cnpq.br/3419623398527291 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (4911262078091389,'http://lattes.cnpq.br/4911262078091389 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0836642763735156,'http://lattes.cnpq.br/0836642763735156 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3006113407201781,'http://lattes.cnpq.br/3006113407201781 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5147836788812000,'http://lattes.cnpq.br/5147836788812000 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3213391944406144,'http://lattes.cnpq.br/3213391944406144 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (4963456464135167,'http://lattes.cnpq.br/4963456464135167 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (7542810330553684,'http://lattes.cnpq.br/7542810330553684 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0445651840195495,'http://lattes.cnpq.br/0445651840195495 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (1366193935168737,'http://lattes.cnpq.br/1366193935168737 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0561795837974018,'http://lattes.cnpq.br/0561795837974018 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5376452909200749,'http://lattes.cnpq.br/5376452909200749 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0859485999444567,'http://lattes.cnpq.br/0859485999444567 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (6246109453810593,'http://lattes.cnpq.br/6246109453810593 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (2609464520533223,'http://lattes.cnpq.br/2609464520533223 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (4988291703607703,'http://lattes.cnpq.br/4988291703607703 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (8438856690765294,'http://lattes.cnpq.br/8438856690765294 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (1436760007278366,'http://lattes.cnpq.br/1436760007278366 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3524264298241361,'http://lattes.cnpq.br/3524264298241361 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (2630868677001503,'http://lattes.cnpq.br/2630868677001503 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (8500342018137417,'http://lattes.cnpq.br/8500342018137417 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (1939964953314129,'http://lattes.cnpq.br/1939964953314129 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5721637525245206,'http://lattes.cnpq.br/5721637525245206 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5699689278333466,'http://lattes.cnpq.br/5699689278333466 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (1188055361206114,'http://lattes.cnpq.br/1188055361206114 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (8991027037351508,'http://lattes.cnpq.br/8991027037351508 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3728152362557019,'http://lattes.cnpq.br/3728152362557019 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (6296010765327790,'http://lattes.cnpq.br/6296010765327790 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0062274949550708,'http://lattes.cnpq.br/0062274949550708 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5531142963166222,'http://lattes.cnpq.br/5531142963166222 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0580997618984789,'http://lattes.cnpq.br/0580997618984789 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0271195734028768,'http://lattes.cnpq.br/0271195734028768 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (4281998916165146,'http://lattes.cnpq.br/4281998916165146 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3633451874816212,'http://lattes.cnpq.br/3633451874816212 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (9386874220178227,'http://lattes.cnpq.br/9386874220178227 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (4985491559157022,'http://lattes.cnpq.br/4985491559157022 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (9910460090402916,'http://lattes.cnpq.br/9910460090402916 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (9228579214254891,'http://lattes.cnpq.br/9228579214254891 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (7305431752431773,'http://lattes.cnpq.br/7305431752431773 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5393844411346096,'http://lattes.cnpq.br/5393844411346096 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (9843264750053109,'http://lattes.cnpq.br/9843264750053109 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (8915937919750384,'http://lattes.cnpq.br/8915937919750384 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (9792994865902593,'http://lattes.cnpq.br/9792994865902593 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (9476068193493810,'http://lattes.cnpq.br/9476068193493810 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0594196392487193,'http://lattes.cnpq.br/0594196392487193 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (7131414783841626,'http://lattes.cnpq.br/7131414783841626 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (9561797798603672,'http://lattes.cnpq.br/9561797798603672 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (4033383180932474,'http://lattes.cnpq.br/4033383180932474 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (7671363578256554,'http://lattes.cnpq.br/7671363578256554 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0948223916834250,'http://lattes.cnpq.br/0948223916834250 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3612619381261971,'http://lattes.cnpq.br/3612619381261971 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0152063930197631,'http://lattes.cnpq.br/0152063930197631 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3959587666794415,'http://lattes.cnpq.br/3959587666794415 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (4433119488921195,'http://lattes.cnpq.br/4433119488921195 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (2271811478179514,'http://lattes.cnpq.br/2271811478179514 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (9399964422566176,'http://lattes.cnpq.br/9399964422566176 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (6279974411948216,'http://lattes.cnpq.br/6279974411948216 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (8976791755900010,'http://lattes.cnpq.br/8976791755900010 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (4945262958389466,'http://lattes.cnpq.br/4945262958389466 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (8697221494886208,'http://lattes.cnpq.br/8697221494886208 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (4314966200727513,'http://lattes.cnpq.br/4314966200727513 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (1314950090980188,'http://lattes.cnpq.br/1314950090980188 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (7286472458791026,'http://lattes.cnpq.br/7286472458791026 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (6188797190643412,'http://lattes.cnpq.br/6188797190643412 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3903919291725976,'http://lattes.cnpq.br/3903919291725976 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5033314173131489,'http://lattes.cnpq.br/5033314173131489 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0364103051736128,'http://lattes.cnpq.br/0364103051736128 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (8199192901622333,'http://lattes.cnpq.br/8199192901622333 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0046237693009702,'http://lattes.cnpq.br/0046237693009702 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3092580934671870,'http://lattes.cnpq.br/3092580934671870 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (4974922184603591,'http://lattes.cnpq.br/4974922184603591 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (8307135659768882,'http://lattes.cnpq.br/8307135659768882 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3332190265116367,'http://lattes.cnpq.br/3332190265116367 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (6468076577335847,'http://lattes.cnpq.br/6468076577335847 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (6759005428128566,'http://lattes.cnpq.br/6759005428128566 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (1251450318945989,'http://lattes.cnpq.br/1251450318945989 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (2013748165081615,'http://lattes.cnpq.br/2013748165081615 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (7440190895884915,'http://lattes.cnpq.br/7440190895884915 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (7134095439585865,'http://lattes.cnpq.br/7134095439585865 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (7437590156111266,'http://lattes.cnpq.br/7437590156111266 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (4829778848235742,'http://lattes.cnpq.br/4829778848235742 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3440167117711504,'http://lattes.cnpq.br/3440167117711504 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (8556107912933904,'http://lattes.cnpq.br/8556107912933904 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0477788198290554,'http://lattes.cnpq.br/0477788198290554 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3839725324091323,'http://lattes.cnpq.br/3839725324091323 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (8494783082862407,'http://lattes.cnpq.br/8494783082862407 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (8344173755632684,'http://lattes.cnpq.br/8344173755632684 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5172045004216232,'http://lattes.cnpq.br/5172045004216232 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (4580951637849908,'http://lattes.cnpq.br/4580951637849908 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5551381817732211,'http://lattes.cnpq.br/5551381817732211 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (2572086433612054,'http://lattes.cnpq.br/2572086433612054 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (6537996804614592,'http://lattes.cnpq.br/6537996804614592 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (2050521351934466,'http://lattes.cnpq.br/2050521351934466 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3309385117531500,'http://lattes.cnpq.br/3309385117531500 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (9313282490043970,'http://lattes.cnpq.br/9313282490043970 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0952274679830204,'http://lattes.cnpq.br/0952274679830204 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (2756753952075393,'http://lattes.cnpq.br/2756753952075393 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (6649796144129435,'http://lattes.cnpq.br/6649796144129435 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (4255375851150386,'http://lattes.cnpq.br/4255375851150386 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (6909005481498739,'http://lattes.cnpq.br/6909005481498739 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (8390543622306236,'http://lattes.cnpq.br/8390543622306236 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5791238224309276,'http://lattes.cnpq.br/5791238224309276 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (6253477923609818,'http://lattes.cnpq.br/6253477923609818 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0328730975862213,'http://lattes.cnpq.br/0328730975862213 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (9254137518065176,'http://lattes.cnpq.br/9254137518065176 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0291373793427638,'http://lattes.cnpq.br/0291373793427638 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (8755104082298597,'http://lattes.cnpq.br/8755104082298597 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (4216261518893448,'http://lattes.cnpq.br/4216261518893448 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0509668485384679,'http://lattes.cnpq.br/0509668485384679 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (8403201845966486,'http://lattes.cnpq.br/8403201845966486 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (9165723122297620,'http://lattes.cnpq.br/9165723122297620 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3529280084215014,'http://lattes.cnpq.br/3529280084215014 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3945660888230811,'http://lattes.cnpq.br/3945660888230811 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (7659000230033082,'http://lattes.cnpq.br/7659000230033082 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5278555276261753,'http://lattes.cnpq.br/5278555276261753 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (4893973422111886,'http://lattes.cnpq.br/4893973422111886 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (2528124034664528,'http://lattes.cnpq.br/2528124034664528 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5473476417303954,'http://lattes.cnpq.br/5473476417303954 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (2884802638051403,'http://lattes.cnpq.br/2884802638051403 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3043399319231301,'http://lattes.cnpq.br/3043399319231301 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0478114607811338,'http://lattes.cnpq.br/0478114607811338 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5189245301180193,'http://lattes.cnpq.br/5189245301180193 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3260108628148546,'http://lattes.cnpq.br/3260108628148546 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (2958895713696822,'http://lattes.cnpq.br/2958895713696822 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (7649103160254992,'http://lattes.cnpq.br/7649103160254992 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (2664155593497709,'http://lattes.cnpq.br/2664155593497709 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5364861456395665,'http://lattes.cnpq.br/5364861456395665 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3377974644377234,'http://lattes.cnpq.br/3377974644377234 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (4710310175994133,'http://lattes.cnpq.br/4710310175994133 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (2665371792367653,'http://lattes.cnpq.br/2665371792367653 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5320592730826501,'http://lattes.cnpq.br/5320592730826501 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (9435178393114804,'http://lattes.cnpq.br/9435178393114804 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0794381559000287,'http://lattes.cnpq.br/0794381559000287 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5368368699798711,'http://lattes.cnpq.br/5368368699798711 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0826062363391911,'http://lattes.cnpq.br/0826062363391911 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3169269322323485,'http://lattes.cnpq.br/3169269322323485 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (6768116628110362,'http://lattes.cnpq.br/6768116628110362 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (7629525419175777,'http://lattes.cnpq.br/7629525419175777 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3972787136307157,'http://lattes.cnpq.br/3972787136307157 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (1455747602225273,'http://lattes.cnpq.br/1455747602225273 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5564141620197737,'http://lattes.cnpq.br/5564141620197737 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (4782206027711775,'http://lattes.cnpq.br/4782206027711775 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (2673060331553099,'http://lattes.cnpq.br/2673060331553099 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3038392782039663,'http://lattes.cnpq.br/3038392782039663 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (8115170718000313,'http://lattes.cnpq.br/8115170718000313 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3152213683224776,'http://lattes.cnpq.br/3152213683224776 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (1100247593691444,'http://lattes.cnpq.br/1100247593691444 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3231949862618284,'http://lattes.cnpq.br/3231949862618284 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (1736670287663462,'http://lattes.cnpq.br/1736670287663462 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (1320647554655010,'http://lattes.cnpq.br/1320647554655010 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (6672596173124214,'http://lattes.cnpq.br/6672596173124214 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (1863177057291007,'http://lattes.cnpq.br/1863177057291007 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (2252099162812700,'http://lattes.cnpq.br/2252099162812700 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (7954830438234781,'http://lattes.cnpq.br/7954830438234781 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (1225540330138355,'http://lattes.cnpq.br/1225540330138355 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0239265512781490,'http://lattes.cnpq.br/0239265512781490 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0041476511097254,'http://lattes.cnpq.br/0041476511097254 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (7480049035649106,'http://lattes.cnpq.br/7480049035649106 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (6367014249983851,'http://lattes.cnpq.br/6367014249983851 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0056792282398065,'http://lattes.cnpq.br/0056792282398065 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (6799921244953381,'http://lattes.cnpq.br/6799921244953381 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (2755518418998729,'http://lattes.cnpq.br/2755518418998729 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (4935115730688093,'http://lattes.cnpq.br/4935115730688093 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3615940235723053,'http://lattes.cnpq.br/3615940235723053 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (4138069877722576,'http://lattes.cnpq.br/4138069877722576 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0191130745270756,'http://lattes.cnpq.br/0191130745270756 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (7398514443100551,'http://lattes.cnpq.br/7398514443100551 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (9657534452328375,'http://lattes.cnpq.br/9657534452328375 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (4359820331493446,'http://lattes.cnpq.br/4359820331493446 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5957390805114014,'http://lattes.cnpq.br/5957390805114014 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5028139171066650,'http://lattes.cnpq.br/5028139171066650 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (8807948509480699,'http://lattes.cnpq.br/8807948509480699 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0404624792247041,'http://lattes.cnpq.br/0404624792247041 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3126434433286539,'http://lattes.cnpq.br/3126434433286539 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (4236236725046882,'http://lattes.cnpq.br/4236236725046882 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (1921680094528577,'http://lattes.cnpq.br/1921680094528577 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (7621984053230170,'http://lattes.cnpq.br/7621984053230170 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3547496765385198,'http://lattes.cnpq.br/3547496765385198 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (6574094068007301,'http://lattes.cnpq.br/6574094068007301 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (7864136111570305,'http://lattes.cnpq.br/7864136111570305 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (2389914873551775,'http://lattes.cnpq.br/2389914873551775 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0405498579305700,'http://lattes.cnpq.br/0405498579305700 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0952102997417350,'http://lattes.cnpq.br/0952102997417350 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5971351057949885,'http://lattes.cnpq.br/5971351057949885 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (6399985363412772,'http://lattes.cnpq.br/6399985363412772 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (6020927252631317,'http://lattes.cnpq.br/6020927252631317 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (6822992419992600,'http://lattes.cnpq.br/6822992419992600 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (4803190114541258,'http://lattes.cnpq.br/4803190114541258 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (7410483448026320,'http://lattes.cnpq.br/7410483448026320 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (4986150624706990,'http://lattes.cnpq.br/4986150624706990 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3947125061244712,'http://lattes.cnpq.br/3947125061244712 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5847354145786731,'http://lattes.cnpq.br/5847354145786731 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (4467244689870571,'http://lattes.cnpq.br/4467244689870571 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3522425475777833,'http://lattes.cnpq.br/3522425475777833 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (2917208722028226,'http://lattes.cnpq.br/2917208722028226 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (7708646643282782,'http://lattes.cnpq.br/7708646643282782 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (8553806495108619,'http://lattes.cnpq.br/8553806495108619 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (2197588162397668,'http://lattes.cnpq.br/2197588162397668 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0873865276812393,'http://lattes.cnpq.br/0873865276812393 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (1814998858764422,'http://lattes.cnpq.br/1814998858764422 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (9538909085628035,'http://lattes.cnpq.br/9538909085628035 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (7463894814401016,'http://lattes.cnpq.br/7463894814401016 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (1721617102704861,'http://lattes.cnpq.br/1721617102704861 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (2581158538202725,'http://lattes.cnpq.br/2581158538202725 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3001710102282760,'http://lattes.cnpq.br/3001710102282760 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (6654280379842044,'http://lattes.cnpq.br/6654280379842044 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (1740093316970974,'http://lattes.cnpq.br/1740093316970974 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5530194327085060,'http://lattes.cnpq.br/5530194327085060 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3253094583924786,'http://lattes.cnpq.br/3253094583924786 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3270989786290783,'http://lattes.cnpq.br/3270989786290783 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0152260110100348,'http://lattes.cnpq.br/0152260110100348 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (9712629999259131,'http://lattes.cnpq.br/9712629999259131 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (4593672422058186,'http://lattes.cnpq.br/4593672422058186 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (6814573530007964,'http://lattes.cnpq.br/6814573530007964 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5161871610763686,'http://lattes.cnpq.br/5161871610763686 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (7834118615333449,'http://lattes.cnpq.br/7834118615333449 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5064234947409203,'http://lattes.cnpq.br/5064234947409203 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (4774890477994515,'http://lattes.cnpq.br/4774890477994515 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (7989786925248716,'http://lattes.cnpq.br/7989786925248716 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (6216472524587908,'http://lattes.cnpq.br/6216472524587908 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (5743322664981581,'http://lattes.cnpq.br/5743322664981581 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (7869111463930835,'http://lattes.cnpq.br/7869111463930835 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3428238105973322,'http://lattes.cnpq.br/3428238105973322 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (4288002170442554,'http://lattes.cnpq.br/4288002170442554 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (3773086146144648,'http://lattes.cnpq.br/3773086146144648 ',null);
INSERT INTO `link` (id_link, url, data_cur) VALUES (0094565524057002,'http://lattes.cnpq.br/0094565524057002',null);
insert into `fila_process` values('http://lattes.cnpq.br/0135813952022069',null);
insert into `fila_process` values('http://lattes.cnpq.br/0152063930197631',null);
insert into `fila_process` values('http://lattes.cnpq.br/0152260110100348',null);
insert into `fila_process` values('http://lattes.cnpq.br/0191130745270756',null);
insert into `fila_process` values('http://lattes.cnpq.br/0445651840195495',null);