-- MySQL Script generated by MySQL Workbench
-- 08/30/16 15:37:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Lattes
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Lattes` ;

-- -----------------------------------------------------
-- Schema Lattes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Lattes` DEFAULT CHARACTER SET utf8 ;
USE `Lattes` ;

-- -----------------------------------------------------
-- Table `dim_pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dim_pessoa` ;

CREATE TABLE IF NOT EXISTS `dim_pessoa` (
  `id_user` BIGINT NOT NULL,
  `nm_user` VARCHAR(255) NOT NULL,
  `citacao` LONGTEXT NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dim_tempo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dim_tempo` ;

CREATE TABLE IF NOT EXISTS `dim_tempo` (
  `id_tempo` INT NOT NULL AUTO_INCREMENT,
  `ano_inicial` INT NOT NULL,
  `mes_inicial` INT NULL,
  `ano_final` INT NULL,
  `mes_final` INT NULL,
  PRIMARY KEY (`id_tempo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat_projeto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat_projeto` ;

CREATE TABLE IF NOT EXISTS `fat_projeto` (
  `id_user` BIGINT NOT NULL,
  `id_tempo` INT NOT NULL,
  `tipo` LONGTEXT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` LONGTEXT NULL,
  `situacao` VARCHAR(100) NULL,
  `natureza` VARCHAR(100) NULL,
  `alunos` VARCHAR(255) NULL,
  `integrantes` LONGTEXT NULL,
  `financiador` VARCHAR(255) NULL,
  `producoes` INT NULL,
  INDEX `fk_Projetos_Tempo1_idx` (`id_tempo` ASC),
  PRIMARY KEY (`id_user`, `id_tempo`),
  INDEX `fk_Projetos_dim_Pessoa1_idx` (`id_user` ASC),
  CONSTRAINT `fk_Projetos_Tempo1`
    FOREIGN KEY (`id_tempo`)
    REFERENCES `dim_tempo` (`id_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projetos_dim_Pessoa1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dim_pessoa` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat_formacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat_formacao` ;

CREATE TABLE IF NOT EXISTS `fat_formacao` (
  `id_user` BIGINT NOT NULL,
  `id_tempo` INT NOT NULL,
  `nivel` LONGTEXT NOT NULL,
  `curso` LONGTEXT NOT NULL,
  `local` VARCHAR(255) NOT NULL,
  `titulo` VARCHAR(255) NULL,
  `orientador` VARCHAR(255) NULL,
  `bolsa` VARCHAR(255) NULL,
  PRIMARY KEY (`id_user`, `id_tempo`),
  INDEX `fk_Formacao_Geral_idx` (`id_user` ASC),
  INDEX `fk_Formacao_Tempo1_idx` (`id_tempo` ASC),
  CONSTRAINT `fk_Formacao_Geral`
    FOREIGN KEY (`id_user`)
    REFERENCES `dim_pessoa` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Formacao_Tempo1`
    FOREIGN KEY (`id_tempo`)
    REFERENCES `dim_tempo` (`id_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat_atuacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat_atuacao` ;

CREATE TABLE IF NOT EXISTS `fat_atuacao` (
  `id_user` BIGINT NOT NULL,
  `id_tempo` INT NOT NULL,
  `instituicao` VARCHAR(150) NOT NULL,
  `tipo_vinculo` VARCHAR(45) NULL,
  `enq_funcional` VARCHAR(45) NULL,
  `carga_horaria` INT NULL,
  INDEX `fk_Atuacao_Geral1_idx` (`id_user` ASC),
  INDEX `fk_Atuacao_Tempo1_idx` (`id_tempo` ASC),
  PRIMARY KEY (`id_user`, `id_tempo`),
  CONSTRAINT `fk_Atuacao_Geral1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dim_pessoa` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Atuacao_Tempo1`
    FOREIGN KEY (`id_tempo`)
    REFERENCES `dim_tempo` (`id_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dim_cadastro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dim_cadastro` ;

CREATE TABLE IF NOT EXISTS `dim_cadastro` (
  `id_dataCadastro` INT NOT NULL AUTO_INCREMENT,
  `data_cadastro` DATE NOT NULL,
  PRIMARY KEY (`id_dataCadastro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat_idioma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat_idioma` ;

CREATE TABLE IF NOT EXISTS `fat_idioma` (
  `id_user` BIGINT NOT NULL,
  `data_cadastro` INT NOT NULL,
  `idioma` VARCHAR(45) NOT NULL,
  `le` VARCHAR(45) NOT NULL,
  `fala` VARCHAR(45) NOT NULL,
  `escreve` VARCHAR(45) NOT NULL,
  `compreende` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user`, `data_cadastro`),
  INDEX `fk_idioma_Geral1_idx` (`id_user` ASC),
  INDEX `fk_fat_idioma_dim_cadastro1_idx` (`data_cadastro` ASC),
  CONSTRAINT `fk_idioma_Geral1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dim_pessoa` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fat_idioma_dim_cadastro1`
    FOREIGN KEY (`data_cadastro`)
    REFERENCES `dim_cadastro` (`id_dataCadastro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat_pesquisa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat_pesquisa` ;

CREATE TABLE IF NOT EXISTS `fat_pesquisa` (
  `id_user` BIGINT NOT NULL,
  `data_cadastro` INT NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_user`, `data_cadastro`),
  INDEX `fk_Pesquisa_Geral1_idx` (`id_user` ASC),
  INDEX `fk_fat_pesquisa_dim_cadastro1_idx` (`data_cadastro` ASC),
  CONSTRAINT `fk_Pesquisa_Geral1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dim_pessoa` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fat_pesquisa_dim_cadastro1`
    FOREIGN KEY (`data_cadastro`)
    REFERENCES `dim_cadastro` (`id_dataCadastro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ref_endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ref_endereco` ;

CREATE TABLE IF NOT EXISTS `ref_endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `id_user` BIGINT NOT NULL,
  `local` VARCHAR(255) NOT NULL,
  `cep` VARCHAR(12) NOT NULL,
  `estado` VARCHAR(45) NULL,
  `cidade` VARCHAR(150) NULL,
  `bairro` VARCHAR(150) NULL,
  `logradouro` LONGTEXT NULL,
  `latitude` FLOAT NULL,
  `longitude` FLOAT NULL,
  PRIMARY KEY (`id_endereco`),
  INDEX `fk_ref_Endereco_dim_pessoa1_idx` (`id_user` ASC),
  CONSTRAINT `fk_ref_Endereco_dim_pessoa1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dim_pessoa` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat_premio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat_premio` ;

CREATE TABLE IF NOT EXISTS `fat_premio` (
  `id_user` BIGINT NOT NULL,
  `id_tempo` INT NOT NULL,
  `nome` LONGTEXT NOT NULL,
  `entidade` LONGTEXT NOT NULL,
  INDEX `fk_Premios_Tempo1_idx` (`id_tempo` ASC),
  INDEX `fk_Premios_Geral1_idx` (`id_user` ASC),
  PRIMARY KEY (`id_user`, `id_tempo`),
  CONSTRAINT `fk_Premios_Tempo1`
    FOREIGN KEY (`id_tempo`)
    REFERENCES `dim_tempo` (`id_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Premios_Geral1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dim_pessoa` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curriculum`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curriculum` ;

CREATE TABLE IF NOT EXISTS `curriculum` (
  `data_cadastro` INT NOT NULL,
  `id_curriculo` BIGINT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `url` VARCHAR(200) NOT NULL,
  `content` LONGBLOB NOT NULL,
  PRIMARY KEY (`id_curriculo`, `data_cadastro`),
  INDEX `fk_curriculum_dim_cadastro1_idx` (`data_cadastro` ASC),
  CONSTRAINT `fk_curriculum_dim_cadastro1`
    FOREIGN KEY (`data_cadastro`)
    REFERENCES `dim_cadastro` (`id_dataCadastro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat_corpoEditorial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat_corpoEditorial` ;

CREATE TABLE IF NOT EXISTS `fat_corpoEditorial` (
  `id_user` BIGINT NOT NULL,
  `id_tempo` INT NOT NULL,
  `editorial` LONGTEXT NOT NULL,
  INDEX `fk_CorpoEditorial_Tempo1_idx` (`id_tempo` ASC),
  PRIMARY KEY (`id_user`, `id_tempo`),
  INDEX `fk_CorpoEditorial_Geral1_idx` (`id_user` ASC),
  CONSTRAINT `fk_CorpoEditorial_Tempo1`
    FOREIGN KEY (`id_tempo`)
    REFERENCES `dim_tempo` (`id_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CorpoEditorial_Geral1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dim_pessoa` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat_revisor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat_revisor` ;

CREATE TABLE IF NOT EXISTS `fat_revisor` (
  `id_user` BIGINT NOT NULL,
  `id_tempo` INT NOT NULL,
  `periodico` BLOB NULL,
  `tipo_revisao` VARCHAR(45) NULL,
  `instituicao` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user`, `id_tempo`),
  INDEX `fk_RevisorPeriodico_Tempo1_idx` (`id_tempo` ASC),
  INDEX `fk_RevisorPeriodico_Geral1_idx` (`id_user` ASC),
  CONSTRAINT `fk_RevisorPeriodico_Tempo1`
    FOREIGN KEY (`id_tempo`)
    REFERENCES `dim_tempo` (`id_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RevisorPeriodico_Geral1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dim_pessoa` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat_producao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat_producao` ;

CREATE TABLE IF NOT EXISTS `fat_producao` (
  `id_user` BIGINT NOT NULL,
  `id_tempo` INT NOT NULL,
  `titulo` LONGTEXT NOT NULL,
  `natureza` VARCHAR(255) NULL,
  `tipo` VARCHAR(45) NULL,
  `categoria` VARCHAR(45) NULL,
  `keywords` LONGTEXT NULL,
  `setor` LONGTEXT NULL,
  INDEX `fk_Producoes_Tempo1_idx` (`id_tempo` ASC),
  INDEX `fk_Producoes_Geral1_idx` (`id_user` ASC),
  PRIMARY KEY (`id_user`, `id_tempo`),
  CONSTRAINT `fk_Producoes_Tempo1`
    FOREIGN KEY (`id_tempo`)
    REFERENCES `dim_tempo` (`id_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producoes_Geral1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dim_pessoa` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat_banca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat_banca` ;

CREATE TABLE IF NOT EXISTS `fat_banca` (
  `id_user` BIGINT NOT NULL,
  `id_tempo` INT NOT NULL,
  `banca` VARCHAR(255) NOT NULL,
  `tipo` VARCHAR(255) NULL,
  `natureza` VARCHAR(255) NULL,
  `titulo` LONGTEXT NULL,
  `sobre` LONGTEXT NULL,
  PRIMARY KEY (`id_user`, `id_tempo`),
  INDEX `fk_Bancas_Tempo1_idx` (`id_tempo` ASC),
  INDEX `fk_Bancas_Geral1_idx` (`id_user` ASC),
  CONSTRAINT `fk_Bancas_Tempo1`
    FOREIGN KEY (`id_tempo`)
    REFERENCES `dim_tempo` (`id_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bancas_Geral1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dim_pessoa` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat_evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat_evento` ;

CREATE TABLE IF NOT EXISTS `fat_evento` (
  `id_user` BIGINT NOT NULL,
  `id_tempo` INT NOT NULL,
  `nome` VARCHAR(255) NULL,
  `titulo` VARCHAR(255) NULL,
  `natureza` VARCHAR(255) NULL,
  PRIMARY KEY (`id_user`, `id_tempo`),
  INDEX `fk_Eventos_Tempo1_idx` (`id_tempo` ASC),
  INDEX `fk_Eventos_dim_Pessoa1_idx` (`id_user` ASC),
  CONSTRAINT `fk_Eventos_Tempo1`
    FOREIGN KEY (`id_tempo`)
    REFERENCES `dim_tempo` (`id_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Eventos_dim_Pessoa1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dim_pessoa` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat_orientacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat_orientacao` ;

CREATE TABLE IF NOT EXISTS `fat_orientacao` (
  `id_user` BIGINT NOT NULL,
  `id_tempo` INT NOT NULL,
  `titulo` BLOB NOT NULL,
  `natureza` VARCHAR(255) NULL,
  `tipo` VARCHAR(45) NULL,
  `categoria` VARCHAR(45) NULL,
  `keywords` LONGTEXT NULL,
  `setor` LONGTEXT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user`, `id_tempo`),
  INDEX `fk_Orientacoes_Tempo2_idx` (`id_tempo` ASC),
  INDEX `fk_Orientacoes_Geral2_idx` (`id_user` ASC),
  CONSTRAINT `fk_Orientacoes_Tempo2`
    FOREIGN KEY (`id_tempo`)
    REFERENCES `dim_tempo` (`id_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orientacoes_Geral2`
    FOREIGN KEY (`id_user`)
    REFERENCES `dim_pessoa` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `link`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `link` ;

CREATE TABLE IF NOT EXISTS `link` (
  `id_link` BIGINT NOT NULL,
  `url` VARCHAR(250) NOT NULL,
  `data_cur` DATE NULL,
  PRIMARY KEY (`id_link`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fila_process`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fila_process` ;

CREATE TABLE IF NOT EXISTS `fila_process` (
  `url` VARCHAR(255) NOT NULL,
  `log` BLOB NULL,
  PRIMARY KEY (`url`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat_patente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat_patente` ;

CREATE TABLE IF NOT EXISTS `fat_patente` (
  `id_user` BIGINT NOT NULL,
  `id_tempo` INT NOT NULL,
  `titulo` LONGTEXT NOT NULL,
  `categoria` VARCHAR(255) NULL,
  `instituicao` VARCHAR(255) NULL,
  `descricao` LONGTEXT NULL,
  INDEX `fk_Patentes_dim_tempo1_idx` (`id_tempo` ASC),
  INDEX `fk_Patentes_dim_pessoa1_idx` (`id_user` ASC),
  PRIMARY KEY (`id_user`, `id_tempo`),
  CONSTRAINT `fk_Patentes_dim_tempo1`
    FOREIGN KEY (`id_tempo`)
    REFERENCES `dim_tempo` (`id_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Patentes_dim_pessoa1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dim_pessoa` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat_area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat_area` ;

CREATE TABLE IF NOT EXISTS `fat_area` (
  `id_user` BIGINT NOT NULL,
  `id_tempo` INT NOT NULL,
  `grande_area` VARCHAR(255) NOT NULL,
  `area` VARCHAR(255) NULL,
  `sub_area` VARCHAR(255) NULL,
  `espec` VARCHAR(255) NULL,
  PRIMARY KEY (`id_user`, `id_tempo`),
  INDEX `fk_fat_area_dim_tempo1_idx` (`id_tempo` ASC),
  INDEX `fk_fat_area_dim_pessoa1_idx` (`id_user` ASC),
  CONSTRAINT `fk_fat_area_dim_tempo1`
    FOREIGN KEY (`id_tempo`)
    REFERENCES `dim_tempo` (`id_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fat_area_dim_pessoa1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dim_pessoa` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat_educacaoPopularizacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat_educacaoPopularizacao` ;

CREATE TABLE IF NOT EXISTS `fat_educacaoPopularizacao` (
  `id_user` BIGINT NOT NULL,
  `id_tempo` INT NOT NULL,
  `participantes` VARCHAR(255) NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  `tipo` VARCHAR(255) NOT NULL,
  INDEX `fk_fat_educacaoPopularizacao_dim_pessoa1_idx` (`id_user` ASC),
  INDEX `fk_fat_educacaoPopularizacao_dim_tempo1_idx` (`id_tempo` ASC),
  PRIMARY KEY (`id_tempo`, `id_user`),
  CONSTRAINT `fk_fat_educacaoPopularizacao_dim_pessoa1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dim_pessoa` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fat_educacaoPopularizacao_dim_tempo1`
    FOREIGN KEY (`id_tempo`)
    REFERENCES `dim_tempo` (`id_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `Lattes` ;

-- -----------------------------------------------------
-- Placeholder table for view `campus_cadastrado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_cadastrado` (`local` INT, `cidade` INT, `latitude` INT, `longitude` INT);

-- -----------------------------------------------------
-- View `campus_cadastrado`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `campus_cadastrado` ;
DROP TABLE IF EXISTS `campus_cadastrado`;
USE `Lattes`;
CREATE  OR REPLACE VIEW `campus_cadastrado` AS select local,cidade,latitude,longitude from ref_endereco group by cidade;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
